<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
            	'name' => 'HP',
	            'feature' => "core i5 Ram : 8Go,Disk Dur : 1To , CPU : 3.6 kz",
	            'description' => 'Ce ordinateur est rapide quelque soit votre utilisation',
	            'falsePrice' => 200000,
	            'truePrice' => 180000,
	            'brand_id' => 3,
	            'shop_id' => 10,
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	            'slug' => 'hp',
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/hp.jpg',
            ],
            [
            	'name' => 'Antenne parabolique',
	            'feature' => 'klllll',
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 25000,
	            'truePrice' => 23000,
	            'brand_id' => 4,
	            'shop_id' => 11,
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	            'slug' => 'antenne-parabolique',
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/antenne.jpg',
            ],
            [
            	'name' => 'Télévision',
	            'feature' => "Télé plasma",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 250000,
	            'truePrice' => 220000,
	            'brand_id' => 34,
	            'shop_id' => 6,
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	            'slug' => 'télévision',
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/tele.jpg',
            ],
            [
            	'name' => 'Voitre de luxe',
	            'feature' => "Destroy",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 50000000,
	            'truePrice' => 48000000,
	            'brand_id' => 11,
	            'shop_id' => 1,
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	            'slug' => 'voiture-de-luxe',
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/ma_car.jpg',
            ],
            [
            	'name' => 'volvo',
	            'feature' => "volvol de petite taille, moteur diesel, new",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 20000000,
	            'truePrice' => 18000000,
	            'brand_id' => 11,
	            'shop_id' => 1,
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	            'slug' => 'volvo',
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/volvo1.jpg',
            ],
            [
            	'name' => 'Honda',
	            'feature' => "Honda de petite taille, moteur diesel, new",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 25000000,
	            'truePrice' => 23000000,
	            'brand_id' => 11,
	            'shop_id' => 1,
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	            'slug' => 'honda',
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/honda.jpg',
            ],
            [
            	'name' => 'Range-Roger',
	            'feature' => "Range-Roger de couleur noir, moteur diesel, new",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 35000000,
	            'truePrice' => 34800000,
	            'brand_id' => 11,
	            'shop_id' => 1,
	            'slug' => 'range-rover',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/Range-Rover-Evoque-Face.jpg',
            ],
            [
            	'name' => 'Range-Roger',
	            'feature' => "Range-Roger de couleur rouge, moteur diesel, new",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 35000000,
	            'truePrice' => 34800000,
	            'brand_id' => 11,
	            'shop_id' => 1,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/rang-rover.jpg',
	            'slug' => 'ranger-rover',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'JUKE',
	            'feature' => "juke de couleur jaune, moteur diesel, new",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 35000000,
	            'truePrice' => 34900000,
	            'brand_id' => 11,
	            'shop_id' => 1,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/2014-Nissan-Juke.jpg',
	            'slug' => 'juke',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Laward',
	            'feature' => "mini voiture 4x4 électrique de couleur noir, moteur diesel, new",
	            'description' => 'Laward est voiture pour enfant et se conduit seulement à la maison sous le guide d\'un personnel',
	            'falsePrice' => 1500000,
	            'truePrice' => 1300000,
	            'brand_id' => 11,
	            'shop_id' => 1,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/mini-voiture-4x4-électrique.jpg',
	            'slug' => 'laward',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Micra',
	            'feature' => "Micra de couleur orange, moteur diesel, new",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 5000000,
	            'truePrice' => 4000000,
	            'brand_id' => 11,
	            'shop_id' => 1,
	            'slug' => 'micra',
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/B02E_MICRA.jpg',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Nissan Terra',
	            'feature' => "Nissan Terra de couleur marron, moteur diesel, new",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 75000000,
	            'truePrice' => 72000000,
	            'brand_id' => 11,
	            'shop_id' => 1,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/nissan-terra.jpg',
	            'slug' => 'nissan-terra',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Mercedes benz cabriolet',
	            'feature' => "Mercedes benz cabriolet de couleur blanche, moteur diesel, new",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 5000000,
	            'truePrice' => 4800000,
	            'brand_id' => 11,
	            'shop_id' => 1,
	            'slug' => 'mercdes-benz-cabriolet',
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/Mercedes_benz_cabriolet.jpg',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'PC Apple',
	            'feature' => "core i5 Ram : 6Go, Disk Dur : 1To , CPU : 1.8 kz",
	            'description' => 'PC Apple de couleur noire, new',
	            'falsePrice' => 350000,
	            'truePrice' => 340000,
	            'brand_id' => 3,
	            'shop_id' => 10,
	            'slug' => 'pc-apple',
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/1590679030.png',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'PC HP',
	            'feature' => "core i5 Ram : 16Go, Disk Dur : 1To , CPU : 1.8 kz",
	            'description' => 'PC hp de couleur blanche, new',
	            'falsePrice' => 350000,
	            'truePrice' => 340000,
	            'brand_id' => 3,
	            'shop_id' => 10,
	            'slug' => 'pc-hp',
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/pc01.jpg',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'PC Apple ouphert',
	            'feature' => "core i7 Ram : 16Go, Disk Dur : 1To , CPU : 3.8 kz",
	            'description' => 'PC Apple de couleur blanche, new',
	            'falsePrice' => 350000,
	            'truePrice' => 340000,
	            'brand_id' => 3,
	            'shop_id' => 10,
	            'slug' => 'pc-apple-ouphert',
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/pc02.jpg',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'PC Apple',
	            'feature' => "core i7 Ram : 16Go, Disk Dur : 1To , CPU : 3.8 kz",
	            'description' => 'PC Apple2 de couleur noir, new.',
	            'falsePrice' => 350000,
	            'truePrice' => 340000,
	            'brand_id' => 3,
	            'shop_id' => 10,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/pc03.jpg',
	            'slug' => 'pc-apple',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'PC Apple',
	            'feature' => "core i7 Ram : 16Go, Disk Dur : 2To , CPU : 3.8 kz",
	            'description' => 'PC Apple2 de couleur blanche, new.',
	            'falsePrice' => 400000,
	            'truePrice' => 380000,
	            'brand_id' => 3,
	            'shop_id' => 10,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/pc04.jpg',
	            'slug' => 'pc-apple',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'HP',
	            'feature' => "core i5 Ram : 16Go, Disk Dur : 2To , CPU : 3.8 kz",
	            'description' => 'HP windows de couleur blanche, new',
	            'falsePrice' => 370000,
	            'truePrice' => 350000,
	            'brand_id' => 3,
	            'shop_id' => 10,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/pc05.jpg',
	            'slug' => 'hp',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'PC Manette complet',
	            'feature' => "core i5 Ram : 16Go, Disk Dur : 2To , CPU : 3.8 kz",
	            'description' => 'PC Manette de couleur blanche, new',
	            'falsePrice' => 500000,
	            'truePrice' => 480000,
	            'brand_id' => 3,
	            'shop_id' => 10,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/Ph-derby-manet.jpg',
	            'slug' => 'pc-manette-complet',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'PC alienware laptop',
	            'feature' => "core i3 Ram : 8Go, Disk Dur : 2To , CPU : 3.8 kz",
	            'description' => 'PC alienware laptop de couleur noire, new',
	            'falsePrice' => 600000,
	            'truePrice' => 590000,
	            'brand_id' => 3,
	            'shop_id' => 10,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/alienware-laptop.jpg',
	            'slug' => 'pc-alienware-laptop',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'ouphert',
	            'feature' => "ouphert amazon de couleur noire, new",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 25000,
	            'truePrice' => 24000,
	            'brand_id' => 26,
	            'shop_id' => 10,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/amazon-echodot.jpg',
	            'slug' => 'ouphert',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'télé charp',
	            'feature' => "télé charp  de couleur noire, new",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 80000,
	            'truePrice' => 78000,
	            'brand_id' => 34,
	            'shop_id' => 10,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/1590604925.jpg',
	            'slug' => 'télé-charp',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'ouphert Apple',
	            'feature' => "ouphert Apple Apple de couleur noire, new",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 30000,
	            'truePrice' => 28000,
	            'brand_id' => 26,
	            'shop_id' => 10,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/1590683290.png',
	            'slug' => 'ouphert-apple',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'télé',
	            'feature' => "télé amazon de couleur noire, new",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 50000,
	            'truePrice' => 48000,
	            'brand_id' => 34,
	            'shop_id' => 6,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/5.png',
	            'slug' => 'tele',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Casque sony-headphones',
	            'feature' => "Casque sony-headphones de couleur or, new",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 10000,
	            'truePrice' => 9000,
	            'brand_id' => 26,
	            'shop_id' => 6,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/sony-headphones.jpg',
	            'slug' => 'casque-sony-headphones',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Casque sony',
	            'feature' => "Casque sony de couleur or, new",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 20000,
	            'truePrice' => 19000,
	            'brand_id' => 26,
	            'shop_id' => 6,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/1590678842.png',
	            'slug' => 'casque-sony',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'apple Imac',
	            'feature' => "apple Imac de couleur noire, new",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 100000,
	            'truePrice' => 90000,
	            'brand_id' => 34,
	            'shop_id' => 6,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/apple-Imac.jpg',
	            'slug' => 'apple-imac',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Montre Sony',
	            'feature' => "Montre Sony de couleur or, new",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 15000,
	            'truePrice' => 13000,
	            'brand_id' => 1,
	            'shop_id' => 6,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/9.png',
	            'slug' => 'montre-sony',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'amazon-firestick',
	            'feature' => "amazon-firestick de couleur or, new",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 15000,
	            'truePrice' => 13000,
	            'brand_id' => 1,
	            'shop_id' => 6,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/amazon-firestick.jpg',
	            'slug' => 'amazon-firestick',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'iphone-x',
	            'feature' => "iphone-x de toutes les couleurs, new",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 150000,
	            'truePrice' => 140000,
	            'brand_id' => 1,
	            'shop_id' => 10,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/1590669785.png',
	            'slug' => 'iphone-x',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'banane',
	            'feature' => "banane douce de toutes les qualités",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 1000,
	            'truePrice' => 900,
	            'brand_id' => 18,
	            'shop_id' => 14,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/banana.jpg',
	            'slug' => 'banane',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Mango douce',
	            'feature' => "Mango douce très délicieuse",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 1000,
	            'truePrice' => 900,
	            'brand_id' => 18,
	            'shop_id' => 14,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/mango02.jpg',
	            'slug' => 'mango-douce',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Papaye europeen',
	            'feature' => "Papaye europeen très délicieuse",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 800,
	            'truePrice' => 600,
	            'brand_id' => 18,
	            'shop_id' => 14,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/papapa.jpg',
	            'slug' => 'papaye-europeen',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Carotte',
	            'feature' => "Carotte douce très délicieuse",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 1000,
	            'truePrice' => 900,
	            'brand_id' => 8,
	            'shop_id' => 12,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/carrots.jpg',
	            'slug' => 'carotte',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Mango chaunsa',
	            'feature' => "Mango chaunsa douce très délicieuse",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 1000,
	            'truePrice' => 900,
	            'brand_id' => 18,
	            'shop_id' => 14,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/MANGO-CHAUNSA.jpg',
	            'slug' => 'mango-chaunsa',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Carotte douzaine',
	            'feature' => "Carotte douce très délicieuse",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 3000,
	            'truePrice' => 2700,
	            'brand_id' => 8,
	            'shop_id' => 12,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/cart.jpg',
	            'slug' => 'carotte-douzaine',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Produit bio',
	            'feature' => "product bio très délicieuse",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 1000,
	            'truePrice' => 900,
	            'brand_id' => 8,
	            'shop_id' => 12,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/produits-bio.jpg',
	            'slug' => 'produit-bio',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Verdura à légume',
	            'feature' => "Verdura douce très délicieuse",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 1000,
	            'truePrice' => 900,
	            'brand_id' => 8,
	            'shop_id' => 12,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/Verduras-e-legumes.jpg',
	            'slug' => 'verdura-a-legume',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Carotte europeen',
	            'feature' => "Carotte europeen très douce",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 1500,
	            'truePrice' => 1300,
	            'brand_id' => 8,
	            'shop_id' => 12,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/carot.jpg',
	            'slug' => 'carotte-europeen',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Mangue',
	            'feature' => "Mangue europeen très douce",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 1000,
	            'truePrice' => 900,
	            'brand_id' => 18,
	            'shop_id' => 14,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/mangue.png',
	            'slug' => 'mange',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Tomate naturel',
	            'feature' => "Tomate douce très délicieuse, agricole, Panier",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 1500,
	            'truePrice' => 1300,
	            'brand_id' => 8,
	            'shop_id' => 12,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/tomate.png',
	            'slug' => 'tomate',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Légumes',
	            'feature' => "Ensemble de légume",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 1000,
	            'truePrice' => 900,
	            'brand_id' => 8,
	            'shop_id' => 12,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/legumes.jpg',
	            'slug' => 'legumes',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Légumes',
	            'feature' => "legume en panier",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 5000,
	            'truePrice' => 4000,
	            'brand_id' => 8,
	            'shop_id' => 12,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/legume01.png',
	            'slug' => 'legumes',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Légumes au fruit',
	            'feature' => "légume au fruit très délicieuse",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 2000,
	            'truePrice' => 1800,
	            'brand_id' => 8,
	            'shop_id' => 12,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/legume_au_fruit.jpg',
	            'slug' => 'fruits-et-légumes-de-panier',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Fruit et Légumes',
	            'feature' => "panier remplir de légume douce très délicieuse",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid',
	            'falsePrice' => 5000,
	            'truePrice' => 4500,
	            'brand_id' => 18,
	            'shop_id' => 12,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/fruits-et-légumes-de-panier.jpg',
	            'slug' => 'fruit-legume',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Fruit au légume europeen',
	            'feature' => "panier au Fruit au légume europeen douce très délicieuse",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 15000,
	            'truePrice' => 13000,
	            'brand_id' => 8,
	            'shop_id' => 12,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/fruit_legume.gif',
	            'slug' => 'fruit-au-legume-europeen',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Bannane plantain',
	            'feature' => "Bannane plantain douce très délicieuse",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 500,
	            'truePrice' => 500,
	            'brand_id' => 18,
	            'shop_id' => 14,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/banabers.jfif',
	            'slug' => 'banane-plantain',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Mango Soo ',
	            'feature' => "Mango Soo douce très douce",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 1500,
	            'truePrice' => 1400,
	            'brand_id' => 18,
	            'shop_id' => 14,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/mango-oso.jpg',
	            'slug' => 'mangosso',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Mango Maya',
	            'feature' => "Maya douce très délicieuse",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 15000,
	            'truePrice' => 14000,
	            'brand_id' => 18,
	            'shop_id' => 14,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/maya.jpg',
	            'slug' => 'mango-maya',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Papaye europeen jaune',
	            'feature' => "Papaye europeen douce très délicieuse",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 1500,
	            'truePrice' => 1300,
	            'brand_id' => 18,
	            'shop_id' => 14,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/papaye1.jpg',
	            'slug' => 'papaye-europeen-jaune',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Bijoux en Diamand',
	            'feature' => "Bijoux en Diamand est objet d'art , couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 200000,
	            'truePrice' => 180000,
	            'brand_id' => 30,
	            'shop_id' => 9,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/bijoux5.jpg',
	            'slug' => 'bijoux-en-diamand',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Boucle d\'oreille en Diamand',
	            'feature' => "Boucle d'oreille en Diamand est objet d'art , couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 50000,
	            'truePrice' => 45000,
	            'brand_id' => 30,
	            'shop_id' => 9,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/boucle-d-oreille.jpg',
	            'slug' => 'boucle-d-oreille-en-diaman',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Boucle d\'oreille Lotus en Diamand',
	            'feature' => "Boucle d'oreille Lotus en Diamand est objet d'art , couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 70000,
	            'truePrice' => 68000,
	            'brand_id' => 30,
	            'shop_id' => 9,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/boucle-d-oreille-lotus.jpg',
	            'slug' => 'boucle-d-oreille-lotus-en-diaman',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Bijoux en Or',
	            'feature' => "Bijoux en Or est objet d'art , couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 500000,
	            'truePrice' => 450000,
	            'brand_id' => 30,
	            'shop_id' => 9,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/bijoux.jpg',
	            'slug' => 'bijoux-en-or',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Alicia Carat en Or',
	            'feature' => "Alicia Carat en Or est objet d'art , couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 50000,
	            'truePrice' => 45000,
	            'brand_id' => 29,
	            'shop_id' => 9,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/bijoux7.jpg',
	            'slug' => 'alicia-caraten-or',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Bracelet complet en Or',
	            'feature' => "Bracelet complet en Or est objet d'art , couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 25000,
	            'truePrice' => 23000,
	            'brand_id' => 29,
	            'shop_id' => 9,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/b3.jpg',
	            'slug' => 'bracelet-complet-en-or',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Bague en Diamand',
	            'feature' => "Bague en Diamand est objet d'art , couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 120000,
	            'truePrice' => 100000,
	            'brand_id' => 30,
	            'shop_id' => 9,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/b1.png',
	            'slug' => 'bague-en-diaman',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Bague en Diamand',
	            'feature' => "Bague en Diamand est objet d'art , couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 100000,
	            'truePrice' => 90000,
	            'brand_id' => 30,
	            'shop_id' => 9,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/b2.jpg',
	            'slug' => 'bague-en-diaman',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Colis complet en Diamand',
	            'feature' => "Colis  en Diamand est objet d'art , couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 500000,
	            'truePrice' => 450000,
	            'brand_id' => 29,
	            'shop_id' => 9,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/bc1.jpg',
	            'slug' => 'colis-complet-en-diaman',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Colis en Or',
	            'feature' => "Colis en Or est objet d'art , couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 5200000,
	            'truePrice' => 5100000,
	            'brand_id' => 29,
	            'shop_id' => 9,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/bc2.jpg',
	            'slug' => 'colis-en-or',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Colis complet',
	            'feature' => "Colis Ensemble en Or est objet d'art , couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 50000,
	            'truePrice' => 45000,
	            'brand_id' => 29,
	            'shop_id' => 9,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/bijoux3.jpg',
	            'slug' => 'colis-complet',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Boucle d\oreille en Diamand',
	            'feature' => "Boucle en Diamand est objet d'art , couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 50000,
	            'truePrice' => 45000,
	            'brand_id' => 30,
	            'shop_id' => 9,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/bd2.jpg',
	            'slug' => 'boucle-d-oreille-en-diaman',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Colis en Or complet',
	            'feature' => "Colis en Or complet est objet d'art , couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 54000,
	            'truePrice' => 53000,
	            'brand_id' => 29,
	            'shop_id' => 9,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/bijoux8.jpg',
	            'slug' => 'colis-en-or-noir',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Boucle d\oreille Assanssan',
	            'feature' => "Boucle en Diamand est objet d'art , couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 550000,
	            'truePrice' => 530000,
	            'brand_id' => 30,
	            'shop_id' => 9,
	             'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/boucle-d-oreille2.jpg',
	             'slug' => 'boucle-d-oreille-assanssan',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Bijoux class',
	            'feature' => "Bijoux class en Diamand est objet d'art , couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 550000,
	            'truePrice' => 530000,
	            'brand_id' => 30,
	            'shop_id' => 9,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/bijoux2.jpg',
	            'slug' => 'bijoux-class',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Boucle d\oreille class',
	            'feature' => "Boucle class en Diamand est objet d'art , couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 550000,
	            'truePrice' => 530000,
	            'brand_id' => 30,
	            'shop_id' => 9,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/bd.jpg',
	            'slug' => 'boucle-d-oreille',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Gobelé',
	            'feature' => "Gobelé de class, interieur frigo, couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 2500,
	            'truePrice' => 2300,
	            'brand_id' => 23,
	            'shop_id' => 8,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/gobele01.jpg',
	            'slug' => 'gobelé',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Gobelé',
	            'feature' => "Gobelé de class, interieur frigo, couleur en OR",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 2500,
	            'truePrice' => 2300,
	            'brand_id' => 23,
	            'shop_id' => 8,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/gobele02.jpg',
	            'slug' => 'gobele',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Porte cuillière café',
	            'feature' => "Porte cuillière café couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 15000,
	            'truePrice' => 13000,
	            'brand_id' => 23,
	            'shop_id' => 8,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/porte-cuillere-cafe.jpg',
	            'slug' => 'porte-cuillere-cafe',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Pot  à ustensil ',
	            'feature' => "Pot à ustensil , toutes les couleur",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 2000,
	            'truePrice' => 1500,
	            'brand_id' => 23,
	            'shop_id' => 8,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/pot-a-ustensil18.jpg',
	            'slug' => 'pot-a-ustensil',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Casserolle',
	            'feature' => "Casserolle, couleur transparente",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 30000,
	            'truePrice' => 28000,
	            'brand_id' => 23,
	            'shop_id' => 8,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/ustensil01.jpg',
	            'slug' => 'casserolle',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Casserolle class',
	            'feature' => "Casserolle class, couleur transparente",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 32000,
	            'truePrice' => 31000,
	            'brand_id' => 23,
	            'shop_id' => 8,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/ustensil02.jpg',
	            'slug' => 'casserolle-class',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Casserolle classic',
	            'feature' => "Casserolle classic, couleur noire",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 50000,
	            'truePrice' => 45000,
	            'brand_id' => 23,
	            'shop_id' => 8,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/ustensil04.jpg',
	            'slug' => 'casserolle-classic',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Casserolle à cuisine',
	            'feature' => "Casserolle cuisine, couleur transparente",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 23000,
	            'truePrice' => 21000,
	            'brand_id' => 23,
	            'shop_id' => 8,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/ustensil06.jpg',
	            'slug' => 'casserolle-à-cuisine',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Ustensil complet',
	            'feature' => "Ustensil complet, couleur rouge",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 100000,
	            'truePrice' => 90000,
	            'brand_id' => 23,
	            'shop_id' => 8,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/ustensil07.jpg',
	            'slug' => 'ustensil-complet',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Casserolle cool',
	            'feature' => "Casserolle cool, couleur transparente",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 20000,
	            'truePrice' => 20000,
	            'brand_id' => 23,
	            'shop_id' => 8,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/ustensil10.jpg',
	            'slug' => 'casserolle-cool',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'lousse class',
	            'feature' => "lousse class, couleur transparente",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 5000,
	            'truePrice' => 4500,
	            'brand_id' => 23,
	            'shop_id' => 8,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/ustensil11.jpg',
	            'slug' => 'lousse-class',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'cuillière complet',
	            'feature' => "cuillière complet, couleur marron",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 7000,
	            'truePrice' => 6000,
	            'brand_id' => 23,
	            'shop_id' => 8,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/ustensil12.jpg',
	            'slug' => 'cuillière-complet',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Casserolle complet noir',
	            'feature' => "Casserolle complet noir, couleur noir",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 150000,
	            'truePrice' => 130000,
	            'brand_id' => 23,
	            'shop_id' => 8,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/ustensil17.jpg',
	            'slug' => 'casserolle-complet-noir',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Ustensil complet noir',
	            'feature' => "Ustensil complet noir, couleur noir",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 30000,
	            'truePrice' => 28000,
	            'brand_id' => 23,
	            'shop_id' => 8,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/ustensil03.jpg',
	            'slug' => 'ustensil-complet-noir',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'Ustensil cuisine complet',
	            'feature' => "Ustensil cuisine complet, couleur transparente",
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 130000,
	            'truePrice' => 140000,
	            'brand_id' => 23,
	            'shop_id' => 8,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/ustensil14.jpg',
	            'slug' => 'ustensil-cuisine-complet',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR')
            ],
            [
            	'name' => 'antena parabólica',
	            'feature' => '',
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 50000,
	            'truePrice' => 45000,
	            'brand_id' => 4,
	            'shop_id' => 11,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/antenne1.jpg',
	            'slug' => 'antena-parabólica-AJ-2M',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => 'antene para grundig',
	            'feature' => '',
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 25000,
	            'truePrice' => 23000,
	            'brand_id' => 4,
	            'shop_id' => 11,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/antenne2.jpg',
	            'slug' => 'antene-para-grundig',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => 'antenne parabolic extenne',
	            'feature' => '',
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 25000,
	            'truePrice' => 23000,
	            'brand_id' => 4,
	            'shop_id' => 11,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/antenne3.jpg',
	            'slug' => 'antenne-parabolic-extenne',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => 'antenne strong',
	            'feature' => '',
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 50000,
	            'truePrice' => 45000,
	            'brand_id' => 4,
	            'shop_id' => 11,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/antenne4.jpg',
	            'slug' => 'antenne-strong',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => 'antenne parabolique en aluminiuml',
	            'feature' => '',
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 25000,
	            'truePrice' => 24000,
	            'brand_id' => 4,
	            'shop_id' => 11,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/antenne5.jpg',
	            'slug' => 'antenne-parabolique-en-aluminiuml',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => 'antenne parabolique tp link',
	            'feature' => '',
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 50000,
	            'truePrice' => 45000,
	            'brand_id' => 4,
	            'shop_id' => 11,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/antenne6.jpg',
	            'slug' => 'antenne-parabolique-tp-link',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => 'Fer 10',
	            'feature' => ' Fer de 10',
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 4200,
	            'truePrice' => 4000,
	            'brand_id' => 20,
	            'shop_id' => 2,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/fer10f.jpg',
	            'slug' => 'fer-de-10',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => 'Tôle',
	            'feature' => ' Tôle',
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 4500,
	            'truePrice' => 4200,
	            'brand_id' => 22,
	            'shop_id' => 2,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/tole.jpg',
	            'slug' => 'tole',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => 'Tôle tule',
	            'feature' => '',
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 5000,
	            'truePrice' => 4500,
	            'brand_id' => 22,
	            'shop_id' => 2,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/tole tule.jpg',
	            'slug' => 'tole-tule',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => 'Ciment',
	            'feature' => '',
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 4500,
	            'truePrice' => 4300,
	            'brand_id' => 19,
	            'shop_id' => 2,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/ciment1.jpg',
	            'slug' => 'ciment',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => 'Ciment bouclier',
	            'feature' => '',
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 4500,
	            'truePrice' => 4300,
	            'brand_id' => 19,
	            'shop_id' => 2,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/ciment2.jpg',
	            'slug' => 'ciment-bouclier',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => 'Tôle tule',
	            'feature' => '',
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 4500,
	            'truePrice' => 4200,
	            'brand_id' => 22,
	            'shop_id' => 2,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/toletule1.jpg',
	            'slug' => 'tole-tule',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => 'Fer de 8',
	            'feature' => 'Fer de 8',
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 2500,
	            'truePrice' => 2200,
	            'brand_id' => 20,
	            'shop_id' => 2,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/fer8.jpg',
	            'slug' => 'fer-de-8',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => 'Fer 10',
	            'feature' => ' Fer de 10 importé',
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 4500,
	            'truePrice' => 4400,
	            'brand_id' => 20,
	            'shop_id' => 2,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/fer10.jpg',
	            'slug' => 'fer-de-10',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => ' Cosme',
	            'feature' => 'produit cosmo',
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 2500,
	            'truePrice' => 2200,
	            'brand_id' => 14,
	            'shop_id' => 3,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/cosme.jpg',
	            'slug' => 'cosme',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => ' Cosme parf',
	            'feature' => 'produit cosmo, parfun',
	            'description' => 'Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.',
	            'falsePrice' => 3000,
	            'truePrice' => 2500,
	            'brand_id' => 14,
	            'shop_id' => 3,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/cosme_parf.jpg',
	            'slug' => 'cosme-parf',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => 'Pommade Algolden',
	            'feature' => 'Organic pure en huile',
	            'description' => '.',
	            'falsePrice' => 14000,
	            'truePrice' => 13000,
	            'brand_id' => 14,
	            'shop_id' => 3,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/cosme01.jpg',
	            'slug' => 'pommade-algolden',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => 'Organic Cosmetic',
	            'feature' => 'produit organique, crêmé',
	            'description' => 'produit cosmetique bio aux fraises.',
	            'falsePrice' => 7500,
	            'truePrice' => 7400,
	            'brand_id' => 14,
	            'shop_id' => 3,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/produit-cosmetique-bio-aux-fraises.jpg',
	            'slug' => 'organic-cosmetic',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
             [
            	'name' => 'Afoé Bio',
	            'feature' => 'reparable, crêmé',
	            'description' => 'produit cosmetique bio aux fraises.',
	            'falsePrice' => 6000,
	            'truePrice' => 5500,
	            'brand_id' => 14,
	            'shop_id' => 3,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/cosmetics.jpg',
	            'slug' => 'afoe-bio',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => 'Pommades Bio',
	            'feature' => 'Bio, anti-biotique',
	            'description' => 'Ce produit cosmetique est anti-biotique',
	            'falsePrice' => 6500,
	            'truePrice' => 6000,
	            'brand_id' => 14,
	            'shop_id' => 3,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/cosmetiques-bio-produits.jpg',
	            'slug' => 'pommade-bio',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
            [
            	'name' => 'Dove',
	            'feature' => 'Savon, pommade',
	            'description' => 'Dove est produit cosmetique complet , avec son savon et toutes ses huiles.',
	            'falsePrice' => 6500,
	            'truePrice' => 6000,
	            'brand_id' => 14,
	            'shop_id' => 3,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/Dove.jpg',
	            'slug' => 'dove',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
            ],
	        [
	        	'name' => 'Cosmetics Sothys',
	            'feature' => 'crêmé, doux sur le corps, boite toute couleur',
	            'description' => 'Sthys est un produit cosmetique.',
	            'falsePrice' => 6500,
	            'truePrice' => 6000,
	            'brand_id' => 14,
	            'shop_id' => 3,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/cosme001.jpg',
	            'slug' => 'cosmetics-sothys',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Chaussure Luxe',
	            'feature' => 'luxe, doux au pied',
	            'description' => 'Chaussure luxe pour homme.',
	            'falsePrice' => 25000,
	            'truePrice' => 23000,
	            'brand_id' => 2,
	            'shop_id' => 4,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/Chaussure-homme-luxe.jpg',
	            'slug' => 'chaussure-luxe',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Chaussure beauty',
	            'feature' => 'bottines noires , talon a resine.',
	            'description' => 'chaussure femme beauty girl s bottines noires a talon a resine.',
	            'falsePrice' => 25000,
	            'truePrice' => 23000,
	            'brand_id' => 2,
	            'shop_id' => 4,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/chaussure-femme-beauty.jpg',
	            'slug' => 'chaussure-beauty',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Chaussure tennis',
	            'feature' => 'couleur safran , basket TS990',
	            'description' => 'CHAUSSURES DE TENNIS JAUNE FLUO MULTI COURT.',
	            'falsePrice' => 35000,
	            'truePrice' => 33000,
	            'brand_id' => 2,
	            'shop_id' => 4,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/chaussure2.jpg',
	            'slug' => 'chaussure-tennis',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'chaussure Talon',
	            'feature' => 'Chaussure , genre femme, noir haut',
	            'description' => 'cete chaussure de  femme est très haute',
	            'falsePrice' => 30000,
	            'truePrice' => 27000,
	            'brand_id' => 2,
	            'shop_id' => 4,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/chaussure femme.jpg',
	            'slug' => 'chaussure-talon',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'chaussure adidas',
	            'feature' => '',
	            'description' => 'chaussure adidas-falcon',
	            'falsePrice' => 30000,
	            'truePrice' => 27000,
	            'brand_id' => 2,
	            'shop_id' => 4,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/adidas-falcon.jpg',
	            'slug' => 'chaussure-adidas',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Impermeable chaussure',
	            'feature' => 'golf,anti skid',
	            'description' => 'hommes impermeable chaussures de golf anti skid sp',
	            'falsePrice' => 45000,
	            'truePrice' => 40000,
	            'brand_id' => 2,
	            'shop_id' => 4,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/hommes-impermeable-chaussures.jpg',
	            'slug' => 'impermeable-chaussure',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Chaussure femme',
	            'feature' => 'rouge chaussure, genre femme',
	            'description' => 'chaussures-femme-rouge',
	            'falsePrice' => 45000,
	            'truePrice' => 40000,
	            'brand_id' => 2,
	            'shop_id' => 4,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/chaussures-femme-rouge.jpg',
	            'slug' => 'chaussure-femme',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Chaussure',
	            'feature' => 'blanc, impécable',
	            'description' => 'chaussures de ville homme cuir suede derby noir',
	            'falsePrice' => 52000,
	            'truePrice' => 50000,
	            'brand_id' => 2,
	            'shop_id' => 4,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/chaussures-de-ville.jpg',
	            'slug' => 'chaussure',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Chaussure Suede derby',
	            'feature' => 'en cuir , noir',
	            'description' => 'chaussures de ville homme cuir suede derby',
	            'falsePrice' => 50000,
	            'truePrice' => 45000,
	            'brand_id' => 2,
	            'shop_id' => 4,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/chaussure1.jpg',
	            'slug' => 'chaussure-suede-derby',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'chaussure Salonner',
	            'feature' => 'vert, crampon',
	            'description' => 'chaussure de ville homme, à crampon',
	            'falsePrice' => 50000,
	            'truePrice' => 45000,
	            'brand_id' => 2,
	            'shop_id' => 4,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/chaussure homme.jpg',
	            'slug' => 'chaussure-salonner',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Fauteuil salon reggiano',
	            'feature' => 'en resine tressee arrondie grise 6 places table avec canape meridienne et 2 poufs encastrables',
	            'description' => 'ce fauteuil est en resine tressee arrondie grise 6 places table avec canape meridienne et 2 poufs encastrables',
	            'falsePrice' => 150000,
	            'truePrice' => 130000,
	            'brand_id' => 32,
	            'shop_id' => 5,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/fauteuil-salon2.jpg',
	            'slug' => 'fauteuil-salon-reggiano',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Salon de jardin',
	            'feature' => 'confortable, belle , impécable',
	            'description' => 'salon de jardin reggiano en resine tressee arrondie grise 6 places table avec canape meridienne et 2 poufs encastrables',
	            'falsePrice' => 200000,
	            'truePrice' => 180000,
	            'brand_id' => 32,
	            'shop_id' => 5,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/salon-de-jardin.jpg',
	            'slug' => 'salon-de-jardin',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Divan Salon',
	            'feature' => 'Impécable, confortable, cool',
	            'description' => 'ensemble salon de jardin',
	            'falsePrice' => 180000,
	            'truePrice' => 160000,
	            'brand_id' => 32,
	            'shop_id' => 5,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/ensemble-salon-de-jardin.jpg',
	            'slug' => 'divan-salon',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Salon',
	            'feature' => 'ensemble salon de jardin confortable',
	            'description' => 'ensemble salon de jardin',
	            'falsePrice' => 160000,
	            'truePrice' => 150000,
	            'brand_id' => 32,
	            'shop_id' => 5,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/salon2.jpg',
	            'slug' => 'salon',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Salon de jardin Resine',
	            'feature' => '4 places , confortable',
	            'description' => 'salon de jardin 4 places en resine noir',
	            'falsePrice' => 160000,
	            'truePrice' => 150000,
	            'brand_id' => 32,
	            'shop_id' => 5,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/salon.jpg',
	            'slug' => 'salon-de-jardin-resine',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Salon de jardin',
	            'feature' => 'encastrable 2 fauteuils m',
	            'description' => 'ensemble salon de jardin encastrable 2 fauteuils m',
	            'falsePrice' => 220000,
	            'truePrice' => 210000,
	            'brand_id' => 32,
	            'shop_id' => 5,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/ensemble-salon.jpg',
	            'slug' => 'salon-de-jardin',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Salon de jardin Toronto',
	            'feature' => 'confortable, moux , doux, ',
	            'description' => 'salon-de-jardin-en-resine-tressee-toronto-bis-atlanta-noir-1',
	            'falsePrice' => 240000,
	            'truePrice' => 230000,
	            'brand_id' => 32,
	            'shop_id' => 5,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/salon3.jpg',
	            'slug' => 'salon-de-jardin-toronto',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Salon de jardin Tressee',
	            'feature' => 'confortable, moux , doux',
	            'description' => 'salon de jardin resine tressee gris 2-personnes',
	            'falsePrice' => 280000,
	            'truePrice' => 270000,
	            'brand_id' => 32,
	            'shop_id' => 5,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/salon-de-jardin-en-resine-tressee.jpg',
	            'slug' => 'salon-de-jardin-tresse',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        
	        [
	        	'name' => 'Table Haute',
	            'feature' => 'table haute jardin de 6 tabourets rotin noir',
	            'description' => 'cette table haute jardin de 6 tabourets rotin noir divan',
	            'falsePrice' => 260000,
	            'truePrice' => 250000,
	            'brand_id' => 32,
	            'shop_id' => 5,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/table-haute.jpg',
	            'slug' => 'table-haute',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Poisson Tchilapia',
	            'feature' => 'long , frais, blanc',
	            'description' => 'sardines-premières-fraîches-isolé',
	            'falsePrice' => 2000,
	            'truePrice' => 1500,
	            'brand_id' => 10,
	            'shop_id' => 13,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/sardines-premières-fraîches-isolé.jpg',
	            'slug' => 'poisson-tchilapia',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Poisson Cap',
	            'feature' => 'tête large et long',
	            'description' => 'premières fraîches isolé, cuisine réuissie',
	            'falsePrice' => 3000,
	            'truePrice' => 2500,
	            'brand_id' => 10,
	            'shop_id' => 13,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/bar_000.jpg',
	            'slug' => 'poisson-cap',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Poisson frais',
	            'feature' => 'frais maquereau indien rondes',
	            'description' => 'maquereau est poisson frais d\'indien et rond',
	            'falsePrice' => 12500,
	            'truePrice' => 11500,
	            'brand_id' => 10,
	            'shop_id' => 13,
                'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/entiers-frais-maquereau-indien-rondes-.jpg',
                'slug' => 'poisson-frais',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Poisson frais',
	            'feature' => 'long, rouge, doux',
	            'description' => 'maquereau indien rond',
	            'falsePrice' => 10500,
	            'truePrice' => 10000,
	            'brand_id' => 10,
	            'shop_id' => 13,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/bar-vide.jpg',
	            'slug' => 'poisson-frais',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Poisson maquereau',
	            'feature' => 'frais, en carton',
	            'description' => 'entiers frais maquereau indien rondes',
	            'falsePrice' => 1500,
	            'truePrice' => 1400,
	            'brand_id' => 10,
	            'shop_id' => 13,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/poison.jpg',
	            'slug' => 'poisson-laquereau',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Poisson mulet',
	            'feature' => 'poisson mulet, long, en carton',
	            'description' => 'poisson frais mulet carton',
	            'falsePrice' => 25000,
	            'truePrice' => 23000,
	            'brand_id' => 10,
	            'shop_id' => 13,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/poisson-frais-mulet-carton-de.jpg',
	            'slug' => 'poisson-mullet',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Poisson frais',
	            'feature' => 'poisson, riche en calcium',
	            'description' => 'poisson-frais-isole est un poisson qui est spécial',
	            'falsePrice' => 18000,
	            'truePrice' => 17000,
	            'brand_id' => 10,
	            'shop_id' => 13,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/poisson-frais-isole.jpg',
	            'slug' => 'poisson-frais',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Maïs',
	            'feature' => 'Maïs rouge, africain',
	            'description' => 'ce produit est impécable, Maïs rouge est repond a tout met',
	            'falsePrice' => 25000,
	            'truePrice' => 25000,
	            'brand_id' => 17,
	            'shop_id' => 15,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/maïs.jpg',
	            'slug' => 'mais',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Monica macaroni',
	            'feature' => 'Monica Spagettie, riz en calcium',
	            'description' => 'ce produit est impécable, Monica est une pâte de mille',
	            'falsePrice' => 12000,
	            'truePrice' => 12000,
	            'brand_id' => 37,
	            'shop_id' => 15,
                'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/monica macaroni.jpg',
                'slug' => 'monica-macaroni',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Mattanti',
	            'feature' => 'Spagettie pate de mille, riche en calcium',
	            'description' => 'ce produit est impécable, Mattanti est une pâte de mille.',
	            'falsePrice' => 12500,
	            'truePrice' => 11500,
	            'brand_id' => 37,
	            'shop_id' => 15,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/macaroni.jpg',
	            'slug' => 'mattanti',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Riz',
	            'feature' => 'riz gain long, blanc',
	            'description' => 'Riz 5kg',
	            'falsePrice' => 12000,
	            'truePrice' => 11000,
	            'brand_id' => 17,
	            'shop_id' => 15,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/riz 5kg.jpg',
	            'slug' => 'riz',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	         [
	        	'name' => 'Sac de riz',
	            'feature' => 'riz en sac, grain long',
	            'description' => 'Riz 5kg',
	            'falsePrice' => 25000,
	            'truePrice' => 23000,
	            'brand_id' => 17,
	            'shop_id' => 15,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/sac-de-riz.jpg',
	            'slug' => 'sac-de-riz',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Riz parfume',
	            'feature' => 'riz taillandais, long grain',
	            'description' => 'riz-parfume-lotus-sac-de-1kg-20kg',
	            'falsePrice' => 1200,
	            'truePrice' => 1000,
	            'brand_id' => 37,
	            'shop_id' => 15,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/riz-parfume-lotus-sac-de-1kg-20kg.jpg',
	            'slug' => 'riz-parfume',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
	        [
	        	'name' => 'Tomate en boite',
	            'feature' => 'Tomate naturel, en boite',
	            'description' => 'tomate en boite',
	            'falsePrice' => 1200,
	            'truePrice' => 1000,
	            'brand_id' => 37,
	            'shop_id' => 15,
	            'mainImage' => !\App::environment('local') ? 'public' : ''.'storage/images/products/tomate en boite.jpg',
	            'slug' => 'tomate-en-boite',
	            'created_at' => Carbon::now()->locale('fr_FR'),
	            'updated_at' => Carbon::now()->locale('fr_FR'),
	        ],
        ]);
    }
}
