<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ShopsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      	DB::table('shops')->insert([
            [
            	'name' => 'Ariel Shop',
                'numberIFU' => '0258748230470',
                'paper_RCCM' => 'storage/images/shops/papers/papers12.jpg',
	            'domain' => 'Véhicule',
	            'address' => 'llot: 0000-Maison DEGLA , City-ITTA, Yaoundé, Cameroun',
                'logo' => 'storage/images/shops/logos/arielshop.png',
                'paper_validate' => 'storage/images/shops/papers/paper01.jpg',
	            'user_id' => 2,
                'confirmationToken' => null,
	            'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
            ],
            [
            	'name' => 'FIFONSI Shop',
                'numberIFU' => '7896542530174',
                'paper_RCCM' => 'storage/images/shops/papers/papers12.jpg',
	            'domain' => 'Quincailllérie',
	            'address' => 'llot: 0450-Maison FANTODJI , GBODJE, Abomey-calavi, Bénin',
                'logo' => 'storage/images/shops/logos/fifonsi.png',
                'paper_validate' => 'storage/images/shops/papers/paper13.jpg',
	            'user_id' => 11,
                'confirmationToken' => null,
	            'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
            ],
            [
            	'name' => 'Hermy Shopy',
                'numberIFU' => '0258848230470',
                'paper_RCCM' => 'storage/images/shops/papers/papers12.jpg',
	            'domain' => 'Cosmétiques & Beauté',
	            'address' => 'llot: 0000-Maison VODOUNNOU , bambanco, Conakry, Guinée',
                'logo' => 'storage/images/shops/logos/hermyshopy.png',
                'paper_validate' => 'storage/images/shops/papers/paper14.jpg',
	            'user_id' => 8,
                'confirmationToken' => null,
	            'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lucie Shop',
                'numberIFU' => '0261338231470',
                'paper_RCCM' => 'storage/images/shops/papers/papers12.jpg',
                'domain' => 'Chaussure',
                'address' => 'llot: 0111-Maison ADJOUA , Gona city, Gona, République démocratique Congo',
                'logo' => 'storage/images/shops/logos/lucishop.png',
                'paper_validate' => 'storage/images/shops/papers/paper02.jpg',
                'user_id' => 19,
                'confirmationToken' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
            	'name' => 'Fabre Vente',
                'numberIFU' => '0258758230470',
                'paper_RCCM' => 'storage/images/shops/papers/papers12.jpg',
	            'domain' => 'Meubles de Salon',
	            'address' => 'llot: 0880-Maison AKPOVI , Accra-ville, Accra, Ghana',
                'logo' => 'storage/images/shops/logos/fabrevente.png',
                'paper_validate' => 'storage/images/shops/papers/paper03.jpg',
	            'user_id' => 2,
                'confirmationToken' => null,
	            'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'MamanFabre Shop',
                'numberIFU' => '0258758230471',
                'paper_RCCM' => 'storage/images/shops/papers/papers12.jpg',
                'domain' => 'Commerce Général',
                'address' => "llot: 0500-Maison AKOTOGNON , Yopougon, Abidjan, Côte d'Ivoire",
                'logo' => 'storage/images/shops/logos/mamanfabre.png',
                'paper_validate' => 'storage/images/shops/papers/paper04.jpg',
                'user_id' => 16,
                'confirmationToken' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'CITECH Market',
                'numberIFU' => '3255148250470',
                'paper_RCCM' => 'storage/images/shops/papers/papers12.jpg',
                'domain' => 'Electronique',
                'address' => 'llot: 1101-Maison SOSSOU , Agori, calavi, Bénin',
                'logo' => null,
                'paper_validate' => null,
                'user_id' => 25,
                'confirmationToken' => 'CITECHestbloqe',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Electro Menage',
                'numberIFU' => '0261718231470',
                'paper_RCCM' => 'storage/images/shops/papers/papers12.jpg',
                'domain' => 'Electromenagère',
                'address' => 'llot: 0111-Maison YAO ADJOUA , Mamdiola, Kinshasa, RDC',
                'logo' => 'storage/images/shops/logos/fraicheurshopy.png',
                'paper_validate' => 'storage/images/shops/papers/paper06.jpg',
                'user_id' => 19,
                'confirmationToken' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kelly-Shop',
                'numberIFU' => '0257798230479',
                'paper_RCCM' => 'storage/images/shops/papers/papers12.jpg',
                'domain' => "Coliers & Bijoux",
                'address' => 'llot: 0140-Maison FAGBE , Toudis, Abudja, Nigeria',
                'logo' => 'storage/images/shops/logos/kellyshop.png',
                'paper_validate' => 'storage/images/shops/papers/paper07.jpg',
                'user_id' => 24,
                'confirmationToken' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Fabre Shop',
                'numberIFU' => '0258758230472',
                'paper_RCCM' => 'storage/images/shops/papers/papers12.jpg',
                'domain' => 'Ordinateurs',
                'address' => "llot: 0880-Maison DEGLA , daloa-coin, Yamoussoukro, Côte d'Ivoire ",
                'logo' => 'storage/images/shops/logos/fabreshop.png',
                'paper_validate' => 'storage/images/shops/papers/paper09.jpg',
                'user_id' => 21,
                'confirmationToken' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sokam Shop',
                'numberIFU' => '0258758230470',
                'paper_RCCM' => 'storage/images/shops/papers/papers12.jpg',
                'domain' => 'Antênne Parabolique',
                'address' => 'llot: 0000-Maison SODEGLA , Monrovia ville, Monrovia, Liberia',
                'logo' => 'storage/images/shops/logos/sokamshop.png',
                'paper_validate' => null,
                'user_id' => 3,
                'confirmationToken' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Agro-Aliment',
                'numberIFU' => '0258748230470',
                'paper_RCCM' => 'storage/images/shops/papers/papers12.jpg',
                'domain' => 'Légume et tubercule',
                'address' => 'llot: 1001-Maison DEGLA AKPOVI , Saint Rita, Cotonou, Bénin',
                'logo' => 'storage/images/shops/logos/agroaliment.png',
                'paper_validate' => 'storage/images/shops/papers/paper10.jpg',
                'user_id' => 22,
                'confirmationToken' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Soso Shop',
                'numberIFU' => '0255148230470',
                'paper_RCCM' => 'storage/images/shops/papers/papers12.jpg',
                'domain' => 'Poissonnerie',
                'address' => 'llot: 1101-Maison SOSO , New-city, Kumassi, Ghana',
                'logo' => 'storage/images/shops/logos/sososhop.png',
                'paper_validate' => 'storage/images/shops/papers/paper11.jpg',
                'user_id' => 5,
                'confirmationToken' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Fabiola Market',
                'numberIFU' => '3255148230470',
                'paper_RCCM' => 'storage/images/shops/papers/papers12.jpg',
                'domain' => 'Fruit ',
                'address' => 'llot: 1101-Maison GBADUIDI , mansi, Accra, Ghana',
                'logo' => 'storage/images/shops/logos/fabiolamarket.png',
                'paper_validate' => 'storage/images/shops/papers/paper12.jpg',
                'user_id' => 7,
                'confirmationToken' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], 
            [
                'name' => 'Karimaman Market',
                'numberIFU' => '3255148230470',
                'paper_RCCM' => 'storage/images/shops/papers/papers12.jpg',
                'domain' => 'Commerce Général',
                'address' => 'llot: 1101-Maison DANHA , Aglouza, Porto-novo, Bénin',
                'logo' => 'storage/images/shops/logos/Karimaman.png',
                'paper_validate' => 'storage/images/shops/papers/paper12.jpg',
                'user_id' => 26,
                'confirmationToken' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ] 
        ]);  
    }
}
